version: '3'

services:
  app:
    build: .
    container_name: jab-api
    volumes:
      - .:/home/node/app
    ports:
      - "3001:3001"
    depends_on:
      - jab

  db:
    image: postgres:9.6.24
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
